const MIN_PLAYERS=3,MAX_PLAYERS=10;
const state={players:['Player 1','Player 2','Player 3'],scores:{},roundPoints:{},word:null,imposter:null,votes:{},revealIndex:0,voterIndex:0,lastWord:null,phase:'menu'};
const app=document.getElementById('app');
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const fallbackWords=[
 {word:'Pizza',word_hi:'पिज़्ज़ा',category:'FOOD',category_hi:'भोजन'},
 {word:'Burger',word_hi:'बर्गर',category:'FOOD',category_hi:'भोजन'},
 {word:'Biryani',word_hi:'बिरयानी',category:'FOOD',category_hi:'भोजन'},
 {word:'Dosa',word_hi:'डोसा',category:'FOOD',category_hi:'भोजन'},
 {word:'Mango',word_hi:'आम',category:'FRUITS',category_hi:'फल'},
 {word:'Apple',word_hi:'सेब',category:'FRUITS',category_hi:'फल'},
 {word:'Lion',word_hi:'शेर',category:'ANIMALS',category_hi:'जानवर'},
 {word:'Tiger',word_hi:'बाघ',category:'ANIMALS',category_hi:'जानवर'},
 {word:'Elephant',word_hi:'हाथी',category:'ANIMALS',category_hi:'जानवर'},
 {word:'Cricket',word_hi:'क्रिकेट',category:'SPORTS',category_hi:'खेल'},
 {word:'Football',word_hi:'फ़ुटबॉल',category:'SPORTS',category_hi:'खेल'},
 {word:'Chess',word_hi:'शतरंज',category:'SPORTS',category_hi:'खेल'},
 {word:'Tea',word_hi:'चाय',category:'DRINKS',category_hi:'पेय'},
 {word:'Coffee',word_hi:'कॉफ़ी',category:'DRINKS',category_hi:'पेय'},
 {word:'Samosa',word_hi:'समोसा',category:'SNACKS & STREET FOOD',category_hi:'स्ट्रीट फ़ूड'}
];
let WORD_DATABASE=[];
function render(html){app.innerHTML=`<div class="app screen">${html}</div>`;window.scrollTo(0,0)}
function btn(text,id='',cls='btn primary'){return `<button class="${cls}"${id?` id="${id}"`:''}>${esc(text)}</button>`}
function menu(){state.phase='menu';render(`<div class="title">IMPOSTER</div><div class="tag">ONE WORD. ONE FAKE. FIND THEM.</div><div class="card"><div class="players" id="players"></div></div><button id="add" class="btn">+ ADD PLAYER</button><button id="play" class="btn primary">PLAY</button><div class="foot">Pass the phone. Find the fake.</div>`);drawPlayers();$('#add').onclick=()=>{if(state.players.length<MAX_PLAYERS){state.players.push(`Player ${state.players.length+1}`);drawPlayers()}};$('#play').onclick=startRound}
function drawPlayers(){const box=$('#players');box.innerHTML=state.players.map((n,i)=>`<div class="player-row"><img src="/assets/main-menu/player-icon.png" onerror="this.style.display='none'"><input value="${esc(n)}" placeholder="Enter a name" data-i="${i}">${state.players.length>MIN_PLAYERS?`<button class="delete" data-i="${i}" aria-label="Remove ${esc(n)}">−</button>`:''}</div>`).join('');box.querySelectorAll('input').forEach(x=>x.oninput=()=>state.players[+x.dataset.i]=x.value);box.querySelectorAll('.delete').forEach(x=>x.onclick=()=>{state.players.splice(+x.dataset.i,1);drawPlayers()});$('#add').disabled=state.players.length>=MAX_PLAYERS}
function startRound(){state.players=state.players.map((n,i)=>n.trim()||`Player ${i+1}`);if(state.players.length<MIN_PLAYERS){alert(`IMPOSTER supports ${MIN_PLAYERS} to ${MAX_PLAYERS} players.`);return}const choices=state.lastWord&&WORD_DATABASE.length>1?WORD_DATABASE.filter(x=>x.word!==state.lastWord):WORD_DATABASE;state.word=choices[Math.floor(Math.random()*choices.length)];state.lastWord=state.word.word;state.imposter=Math.floor(Math.random()*state.players.length);state.revealIndex=0;state.voterIndex=0;state.votes={};state.roundPoints=Object.fromEntries(state.players.map((_,i)=>[i,0]));state.players.forEach((_,i)=>{if(!(i in state.scores))state.scores[i]=0});reveal()}
function reveal(){state.phase='reveal';const i=state.revealIndex,p=state.players[i];render(`<div class="turn-name">${esc(p.toUpperCase())}</div><div class="turn-sub">It's your turn.</div><div class="secret-card"><div class="secret-content" id="secret"><span class="label">PRIVATE ROLE REVEAL</span><span class="value">Tap the curtain</span></div><button class="curtain" id="curtain">TAP HERE TO\nREVEAL YOUR ROLE</button></div><button id="next" class="btn primary" disabled>${i===state.players.length-1?'FINISH REVEAL':`PASS THE PHONE`}</button><div class="privacy">Keep the screen private, then pass the phone.</div>`);$('#curtain').onclick=()=>{const imp=i===state.imposter;$('#secret').innerHTML=imp?`<span class="label">YOUR ROLE</span><span class="value">YOU ARE THE IMPOSTER</span><span class="label">YOUR CATEGORY</span><span class="value">${esc(state.word.category)}</span><span class="hindi">${esc(state.word.category_hi)}</span>`:`<span class="label">WORD</span><span class="value">${esc(state.word.word)}</span><span class="hindi">${esc(state.word.word_hi)}</span><span class="label">CATEGORY</span><span class="value">${esc(state.word.category)}</span><span class="hindi">${esc(state.word.category_hi)}</span>`;$('#curtain').classList.add('hidden');const next=$('#next');next.disabled=false;next.textContent=i===state.players.length-1?'FINISH REVEAL':`PASS THE PHONE TO ${esc(state.players[i+1].toUpperCase())}`};$('#next').onclick=()=>{if(state.revealIndex===state.players.length-1)readyVote();else{state.revealIndex++;reveal()}}}
function readyVote(){state.phase='ready';render(`<div class="ready"><h1>DISCUSS IRL</h1><p>The secret words have been revealed.<br><br>Put the phone down and discuss your clues IRL. Talk it out, make accusations, defend yourself, and decide who the Imposter is.<br><br>When everyone is ready, pick up the phone and continue.</p>${btn('READY TO VOTE?','readyBtn')}</div>`);$('#readyBtn').onclick=()=>{state.voterIndex=0;vote()}}
function vote(){state.phase='voting';const voter=state.players[state.voterIndex];render(`<h1 class="vote-title">${esc(voter.toUpperCase())} — VOTE</h1><div class="vote-question">Who do you think is the Imposter?</div><div class="vote-list">${state.players.map((n,i)=>`<button data-i="${i}">${esc(n.toUpperCase())}</button>`).join('')}</div><button id="confirm" class="btn primary" disabled>CONFIRM VOTE</button><div class="notice" id="notice">Your vote stays private between turns.</div>`);let selected=null;document.querySelectorAll('.vote-list button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.vote-list button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=+b.dataset.i;$('#confirm').disabled=false;$('#notice').textContent=`Selected: ${state.players[selected]}`});$('#confirm').onclick=()=>{state.votes[state.voterIndex]=selected;const last=state.voterIndex===state.players.length-1;render(`<div class="ready"><h1>VOTE LOCKED</h1><p>Pass the phone without showing your choice.</p>${btn(last?'SHOW VOTE SUMMARY':`PASS THE PHONE TO ${state.players[state.voterIndex+1].toUpperCase()}`,'nextVote')}</div>`);$('#nextVote').onclick=()=>{if(last)summary();else{state.voterIndex++;vote()}}}}
function totals(){const out=state.players.map(()=>0);Object.values(state.votes).forEach(target=>{if(Number.isInteger(target)&&target>=0&&target<out.length)out[target]++});return out}
function leaders(t){const max=Math.max(...t);return t.map((v,i)=>v===max?i:-1).filter(i=>i>=0)}
function summary(){state.phase='summary';const t=totals(),l=leaders(t),tie=l.length>1;render(`<div class="summary"><h1>VOTE SUMMARY</h1><div class="card">${state.players.map((n,i)=>`<div class="vote-line ${l.includes(i)?'leader':''}"><span class="name">${esc(n)}</span><div class="bar"><div class="fill" style="width:${(t[i]/Math.max(1,...t))*100}%"></div></div><span class="votes">${t[i]}</span></div>`).join('')}</div><p class="status">${tie?'Tie detected — nobody has a sole top vote.':`Top vote: ${esc(state.players[l[0]])}`}</p>${btn('REVEAL','revealResult')}</div>`);$('#revealResult').onclick=results}
function results(){const t=totals(),l=leaders(t),caught=l.length===1&&l[0]===state.imposter;const points=Object.fromEntries(state.players.map((_,i)=>[i,0]));if(!caught)points[state.imposter]=2;Object.entries(state.votes).forEach(([v,target])=>{const voter=+v;if(voter!==state.imposter)points[voter]=+target===state.imposter?1:-1});Object.keys(points).forEach(i=>{const n=+i;state.scores[n]=(state.scores[n]||0)+points[n];});state.roundPoints=points;state.phase='results';const most=l.length>1?l.map(i=>state.players[i]).join(', '):state.players[l[0]];render(`<div class="summary"><h1>${caught?'IMPOSTER CAUGHT':'IMPOSTER NOT CAUGHT'}</h1><div class="card"><div class="round-info"><div><div class="small">WORD</div><div class="big">${esc(state.word.word)}</div><div class="hindi">${esc(state.word.word_hi)}</div></div><div class="sep"></div><div><div class="small">CATEGORY</div><div class="big">${esc(state.word.category)}</div><div class="hindi">${esc(state.word.category_hi)}</div></div></div></div><div class="card result-card"><div class="small">IMPOSTER</div><div class="big">${esc(state.players[state.imposter])}</div><div class="status">Most votes: ${esc(most)}</div></div><div class="card result-card"><div class="small">SCOREBOARD</div>${state.players.map((n,i)=>`<div class="score-row"><span>${esc(n)}</span><span class="${points[i]>0?'good':points[i]<0?'bad':''}">${points[i]>0?'+':''}${points[i]}</span><span>${state.scores[i]}</span></div>`).join('')}</div>${btn('PLAY AGAIN','again')}${btn('MAIN MENU','home','btn')}</div>`);$('#again').onclick=startRound;$('#home').onclick=menu}
function parseDatabase(text){
 const data=[];
 const categoryRe=/'([^']+)'\s*:\s*\((?:\"([^\"]*)\"|'([^']*)'),\s*(?:\"([^\"]*)\"|'([^']*)')\)/g;
 let m;
 while((m=categoryRe.exec(text))){const category=m[1],catHi=m[2]??m[3]??'',pairs=m[4]??m[5]??'';pairs.split(';').forEach(pair=>{const idx=pair.indexOf('|');if(idx>0)data.push({word:pair.slice(0,idx),word_hi:pair.slice(idx+1),category,category_hi:catHi})})}
 if(!data.length){const simple=/[\"']([^\"']+)[\"']\s*:\s*\([\"']([^\"']*)[\"']\s*,\s*[\"']([^\"']*)[\"']\s*\)/g;while((m=simple.exec(text))){const pairs=m[3].split(';');pairs.forEach(pair=>{const idx=pair.indexOf('|');if(idx>0)data.push({word:pair.slice(0,idx),word_hi:pair.slice(idx+1),category:m[1],category_hi:m[2]})})}}
 return data;
}
async function loadDB(){
 WORD_DATABASE=fallbackWords.slice();
 try{const response=await fetch('/game/word_database.py',{cache:'no-store'});if(response.ok){const text=await response.text();const parsed=parseDatabase(text);if(parsed.length>0)WORD_DATABASE=parsed;}}
 catch(_){/* fallback keeps the game playable */}
}
loadDB().finally(menu);
